export const CASE_CREATE_REQUEST = "CASE_CREATE_REQUEST"
export const CASE_CREATE_SUCCESS = "CASE_CREATE_SUCCESS"
export const CASE_CREATE_FAIL = "CASE_CREATE_FAIL"
export const CASE_CREATE_RESET = "CASE_CREATE_RESET"

export const CASE_TRANSFER_REQUEST = "CASE_TRANSFER_REQUEST"
export const CASE_TRANSFER_SUCCESS = "CASE_TRANSFER_SUCCESS"
export const CASE_TRANSFER_FAIL = "CASE_TRANSFER_FAIL"

export const CASE_DETAILS_REQUEST = "CASE_DETAILS_REQUEST"
export const CASE_DETAILS_SUCCESS = "CASE_DETAILS_SUCCESS"
export const CASE_DETAILS_FAIL = "CASE_DETAILS_FAIL"
export const CASE_DETAILS_RESET = "CASE_DETAILS_RESET"

export const CASE_UPDATE_REQUEST = "CASE_UPDATE_REQUEST"
export const CASE_UPDATE_SUCCESS = "CASE_UPDATE_SUCCESS"
export const CASE_UPDATE_FAIL = "CASE_UPDATE_FAIL"
export const CASE_UPDATE_RESET = "CASE_UPDATE_RESET"

export const CASE_DELETE_REQUEST = "CASE_DELETE_REQUEST"
export const CASE_DELETE_SUCCESS = "CASE_DELETE_SUCCESS"
export const CASE_DELETE_FAIL = "CASE_DELETE_FAIL"

export const CASE_ADDENDUM_REQUEST = "CASE_ADDENDUM_REQUEST"
export const CASE_ADDENDUM_SUCCESS = "CASE_ADDENDUM_SUCCESS"
export const CASE_ADDENDUM_FAIL = "CASE_ADDENDUM_FAIL"

export const CASE_LIST_REQUEST = "CASE_LIST_REQUEST"
export const CASE_LIST_SUCCESS = "CASE_LIST_SUCCESS"
export const CASE_LIST_FAIL = "CASE_LIST_FAIL"

export const CASE_STATISTICS_REQUEST = "CASE_STATISTICS_REQUEST"
export const CASE_STATISTICS_SUCCESS = "CASE_STATISTICS_SUCCESS"
export const CASE_STATISTICS_FAIL = "CASE_STATISTICS_FAIL"

export const APPROVAL_UPDATE_REQUEST = "APPROVAL_UPDATE_REQUEST"
export const APPROVAL_UPDATE_SUCCESS = "APPROVAL_UPDATE_SUCCESS"
export const APPROVAL_UPDATE_FAIL = "APPROVAL_UPDATE_FAIL"