export const CASE_SEARCH_RESET = "CASE_SEARCH_RESET";

export const CASE_SEARCH_PAGE = "CASE_SEARCH_PAGE";
export const CASE_SEARCH_PAGE_SIZE = "CASE_SEARCH_PAGE_SIZE";
export const CASE_SEARCH_SORT = "CASE_SEARCH_SORT";
export const CASE_SEARCH_FILTER = "CASE_SEARCH_FILTER";
export const CASE_SEARCH_FILTER_DATE_REGISTER_GTE =
  "CASE_SEARCH_FILTER_DATE_REGISTER_GTE";
export const CASE_SEARCH_FILTER_DATE_REGISTER_LTE =
  "CASE_SEARCH_FILTER_DATE_REGISTER_LTE";
export const CASE_SEARCH_FILTER_PERSONAL_NUMBER =
  "CASE_SEARCH_FILTER_PERSONAL_NUMBER";
export const CASE_SEARCH_FILTER_INSTITUTION = "CASE_SEARCH_FILTER_INSTITUTION";
